name: 反馈 Bug
description: 反馈遇到的问题
labels: [bug]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        为了使我们更好地帮助你，请提供以下信息。
  - type: textarea
    id: desc
    attributes:
      label: 问题描述
      description: 发生了什么情况？有什么现状？
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 正常情况下应该发生什么
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 实际上发生了什么
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: 截图或录屏
      description: 问题复现时候的截图或录屏
      placeholder: 点击文本框下面小长条可以上传文件
  - type: input
    id: star-ver
    attributes:
      label: 自动锄大地脚本版本
      placeholder: 2.7_test
    validations:
      required: true
  - type: dropdown
    id: server
    attributes:
      label: 星穹铁道区服
      options:
        - 国服
        - 国际服
      description: 目前主要适配国服
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 日志在logs文件夹下。
      placeholder: 点击文本框下面小长条可以上传文件
    validations:
      required: true
